# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created: Sun Jul 31 21:53:13 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(832, 659)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.mplwindow = QtGui.QWidget(self.centralwidget)
        self.mplwindow.setGeometry(QtCore.QRect(12, 12, 585, 629))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplwindow.sizePolicy().hasHeightForWidth())
        self.mplwindow.setSizePolicy(sizePolicy)
        self.mplwindow.setObjectName(_fromUtf8("mplwindow"))
        self.verticalLayoutWidget = QtGui.QWidget(self.mplwindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 581, 501))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.mplvl = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.mplvl.setMargin(0)
        self.mplvl.setObjectName(_fromUtf8("mplvl"))
        self.layoutWidget = QtGui.QWidget(self.mplwindow)
        self.layoutWidget.setGeometry(QtCore.QRect(490, 510, 91, 109))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.res = QtGui.QPushButton(self.layoutWidget)
        self.res.setMaximumSize(QtCore.QSize(91, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.res.setFont(font)
        self.res.setObjectName(_fromUtf8("res"))
        self.verticalLayout_5.addWidget(self.res)
        self.fetch = QtGui.QPushButton(self.layoutWidget)
        self.fetch.setObjectName(_fromUtf8("fetch"))
        self.verticalLayout_5.addWidget(self.fetch)
        self.reset = QtGui.QPushButton(self.layoutWidget)
        self.reset.setObjectName(_fromUtf8("reset"))
        self.verticalLayout_5.addWidget(self.reset)
        self.widget = QtGui.QWidget(self.mplwindow)
        self.widget.setGeometry(QtCore.QRect(10, 510, 476, 123))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.checkBox = QtGui.QCheckBox(self.widget)
        self.checkBox.setMaximumSize(QtCore.QSize(61, 18))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.verticalLayout_7.addWidget(self.checkBox)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.datacube = QtGui.QPushButton(self.widget)
        self.datacube.setMinimumSize(QtCore.QSize(109, 32))
        self.datacube.setMaximumSize(QtCore.QSize(109, 32))
        self.datacube.setObjectName(_fromUtf8("datacube"))
        self.horizontalLayout.addWidget(self.datacube)
        self.dc_nm = QtGui.QLineEdit(self.widget)
        self.dc_nm.setMinimumSize(QtCore.QSize(341, 32))
        self.dc_nm.setMaximumSize(QtCore.QSize(341, 32))
        self.dc_nm.setObjectName(_fromUtf8("dc_nm"))
        self.horizontalLayout.addWidget(self.dc_nm)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.polarization = QtGui.QPushButton(self.widget)
        self.polarization.setMinimumSize(QtCore.QSize(109, 32))
        self.polarization.setMaximumSize(QtCore.QSize(109, 32))
        self.polarization.setObjectName(_fromUtf8("polarization"))
        self.horizontalLayout_2.addWidget(self.polarization)
        self.po_nm = QtGui.QLineEdit(self.widget)
        self.po_nm.setMinimumSize(QtCore.QSize(341, 32))
        self.po_nm.setMaximumSize(QtCore.QSize(341, 32))
        self.po_nm.setObjectName(_fromUtf8("po_nm"))
        self.horizontalLayout_2.addWidget(self.po_nm)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.layoutWidget1 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(607, 12, 202, 475))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.mplfigs = QtGui.QListWidget(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplfigs.sizePolicy().hasHeightForWidth())
        self.mplfigs.setSizePolicy(sizePolicy)
        self.mplfigs.setMinimumSize(QtCore.QSize(200, 311))
        self.mplfigs.setMaximumSize(QtCore.QSize(200, 16777215))
        self.mplfigs.setObjectName(_fromUtf8("mplfigs"))
        self.verticalLayout_2.addWidget(self.mplfigs)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.rho_c_t = QtGui.QLabel(self.layoutWidget1)
        self.rho_c_t.setMinimumSize(QtCore.QSize(121, 21))
        self.rho_c_t.setMaximumSize(QtCore.QSize(121, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica"))
        font.setPointSize(18)
        font.setItalic(True)
        self.rho_c_t.setFont(font)
        self.rho_c_t.setTextFormat(QtCore.Qt.PlainText)
        self.rho_c_t.setObjectName(_fromUtf8("rho_c_t"))
        self.verticalLayout.addWidget(self.rho_c_t)
        self.rho_c = QtGui.QTextBrowser(self.layoutWidget1)
        self.rho_c.setMinimumSize(QtCore.QSize(151, 41))
        self.rho_c.setMaximumSize(QtCore.QSize(151, 41))
        self.rho_c.setObjectName(_fromUtf8("rho_c"))
        self.verticalLayout.addWidget(self.rho_c)
        self.rho_c_t_2 = QtGui.QLabel(self.layoutWidget1)
        self.rho_c_t_2.setMinimumSize(QtCore.QSize(131, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica"))
        font.setPointSize(18)
        font.setItalic(True)
        self.rho_c_t_2.setFont(font)
        self.rho_c_t_2.setTextFormat(QtCore.Qt.PlainText)
        self.rho_c_t_2.setObjectName(_fromUtf8("rho_c_t_2"))
        self.verticalLayout.addWidget(self.rho_c_t_2)
        self.rho_h = QtGui.QTextBrowser(self.layoutWidget1)
        self.rho_h.setMinimumSize(QtCore.QSize(151, 41))
        self.rho_h.setMaximumSize(QtCore.QSize(151, 41))
        self.rho_h.setObjectName(_fromUtf8("rho_h"))
        self.verticalLayout.addWidget(self.rho_h)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.layoutWidget2 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.layoutWidget3 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.layoutWidget4 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(600, 500, 203, 155))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label = QtGui.QLabel(self.layoutWidget4)
        self.label.setMinimumSize(QtCore.QSize(191, 16))
        self.label.setMaximumSize(QtCore.QSize(191, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_6.addWidget(self.label)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.xst = QtGui.QSpinBox(self.layoutWidget4)
        self.xst.setMinimum(-99)
        self.xst.setObjectName(_fromUtf8("xst"))
        self.horizontalLayout_3.addWidget(self.xst)
        self.yst = QtGui.QSpinBox(self.layoutWidget4)
        self.yst.setMinimum(-99)
        self.yst.setObjectName(_fromUtf8("yst"))
        self.horizontalLayout_3.addWidget(self.yst)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_2 = QtGui.QLabel(self.layoutWidget4)
        self.label_2.setMaximumSize(QtCore.QSize(71, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.spsize = QtGui.QLineEdit(self.layoutWidget4)
        self.spsize.setObjectName(_fromUtf8("spsize"))
        self.horizontalLayout_4.addWidget(self.spsize)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.calc = QtGui.QPushButton(self.layoutWidget4)
        self.calc.setMinimumSize(QtCore.QSize(181, 61))
        self.calc.setMaximumSize(QtCore.QSize(181, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.calc.setFont(font)
        self.calc.setObjectName(_fromUtf8("calc"))
        self.verticalLayout_6.addWidget(self.calc)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.res.setText(_translate("MainWindow", "Result", None))
        self.fetch.setText(_translate("MainWindow", "Fetch", None))
        self.reset.setText(_translate("MainWindow", "reset", None))
        self.checkBox.setText(_translate("MainWindow", "grad?", None))
        self.datacube.setText(_translate("MainWindow", "datacube", None))
        self.dc_nm.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None))
        self.polarization.setText(_translate("MainWindow", "polarization", None))
        self.rho_c_t.setText(_translate("MainWindow", "rho^2 - Crosby", None))
        self.rho_c_t_2.setText(_translate("MainWindow", "rho^2 - Hanson", None))
        self.label.setText(_translate("MainWindow", "x-shift         y-shift      (fixed gd)", None))
        self.label_2.setText(_translate("MainWindow", "sample size", None))
        self.calc.setText(_translate("MainWindow", "Calculate fields", None))

